### ISSUE TITLE
Время события

### ISSUE THREAD

**Issue by igor-sergei4** [gotovkk/MeetUpHub#4]
У события есть начало, но нет конца?

start_date – это прямо дата? Детализация времени с шагом в 1 день точно адекватна для синхронизации участников события друг с другом? Если это всё-таки не дата, то имя столбца вводит в заблуждение.

https://github.com/gotovkk/MeetUpHub/blob/6e32839f88c5bef62f3ebefe3157cedcc313f8e2/meetuphub.sql#L24

**Comment by gotovkk** [comment]
Сделал ренейм на start_time, добавил end_time
