### ISSUE TITLE
Дубликация таблиц

### ISSUE THREAD

**Issue by igor-sergei4** [gotovkk/MeetUpHub#5]
Чем тэг отличается от категории? Их связки с событием сейчас полностью идентичны. Только отсутствием описания? Тогда зачем их выделять в разные сущности?

https://github.com/gotovkk/MeetUpHub/blob/6e32839f88c5bef62f3ebefe3157cedcc313f8e2/meetuphub.sql#L59

**Comment by gotovkk** [comment]
Вообще планировал делать систему как на Хабре: с наличием рубрик(категорий) и тегов. Категории служат для общей сортировки ивентов и дают общее представление о нем, а теги служат  для более детального описания события, своеобразная микро-категоризация контента. 
Для примера есть ивент 
Web программирование, но это понятие достаточно обширное для обсуждения(бэк фронт и т.д.) и в тегах более подробно указать: React, Angular (наличие тегов скорее всего будет необязательным)

Либо как вариант просто реализовать категории, но тогда пользователю будет труднее найти 
более подходящее для него мероприятие
